config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar-inverse">
      <div>
        <ul>
            <li>
                <%= link_to "One", pages_one_path %>
            </li>
            <li>
                <%= link_to "Two", pages_two_path %>
            </li>
            <li>
                <%= link_to "Three", pages_three_path%>
            </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h2>Pages#one</h2>
<p>Find me in app/views/pages/one.html.erb</p>
<h1>Rubén Ignacio Castillo Díaz<h1>

app/views/pages/three.html.erb
<h2>Page#three</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt accusamus, est perferendis ipsa tempore reprehenderit libero magnam delectus vitae fugiat sunt quidem quia! Soluta sapiente similique velit, quae assumenda mollitia?</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>
<%= image_tag 'rake_routes.jpeg'%>